version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run:
          name: Set up pipenv.
          command: pip install pipenv
      - run:
          name: Install dependencies.
          command: pipenv install --dev
      - run:
          name: Run tests.
          command: pipenv run py.test -n 4 --cov=UnleashClient
      - run:
          name: Lint code.
          command: pipenv run pylint UnleashClient -f parseable >> pylint.log
      - run:
          name: Run mypy
          command: pipenv run mypy UnleashClient >> mypy.log
      - store_test_results:
          path: .
      - store_artifacts:
          path: pylint.log
      - store_artifacts:
          path: mypy.log

workflows:
  version: 2
  build_and_test:
    jobs:
      - test